networks:
  mynetwork:  # Custom bridge network
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    env_file:
      - .env.docker  # Load credentials securely
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data1:/var/lib/mysql
    networks:
      - mynetwork

  app:
    build: .
    container_name: nodejsapp
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env.docker  # Load .env variables for Node.js
    environment:
      DB_HOST: ${DB_HOST}  # Will be set from .env
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - mynetwork

volumes:
  mysql_data1:
